### ISSUE TITLE
Use empty string as label-prefix input

### ISSUE THREAD

**Issue by nyjr10025** [actions-ecosystem/action-release-label#15]
## What happened

Trying to use the action with no prefix. I want to use the simple labels of `patch`, `minor`, and `major` instead of prefixing them with `release/` on my PR's. 

The action ran without issue but output no `level` after putting an empty string for `label_prefix` instead of using the `release/` default prefix. The debug logs showed `no release label` after running.

## What you expected to happen
the action to output a `level` associated with one of the follow PR tags: `patch`, `minor`, and `major` as inputs

## How to reproduce it
```yaml
name: Test Repro

on:
  pull_request:
    types:
      - closed
    branches: 
      - 'main'

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-get-merged-pull-request@v1
        id: get-merged-pull-request
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions-ecosystem/action-release-label@v1
        id: release-label
        if: ${{ steps.get-merged-pull-request.outputs.title != null }}
        with:
          label_prefix: ""
          labels: ${{ steps.get-merged-pull-request.outputs.labels }}

      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
        if: ${{ steps.release-label.outputs.level != null }}
        with:
          semver_only: true
...
```
The last step will be skipped since steps.release-label.outputs.level == null

## Environment

Not sure what is meant here. As in like what environment in GitHub Actions?
